---
name: Release

on:
  push:
    tags:
      - "hdf5-src-v*"
      - "hdf5-sys-v*"
      - "hdf5-derive-v*"
      - "hdf5-types-v*"
      - "hdf5-v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Install libhdf5
      run: sudo apt-get update && sudo apt-get install libhdf5-dev
    - name: Install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Publish hdf5-src
      if: "${{ startsWith(github.ref_name, 'hdf5-src-v') }}"
      run: cargo publish --package hdf5-metno-src --token "${{ secrets.CRATES_IO_TOKEN }}"
    - name: Publish hdf5-sys
      if: "${{ startsWith(github.ref_name, 'hdf5-sys-v') }}"
      run: cargo publish --package hdf5-metno-sys --token "${{ secrets.CRATES_IO_TOKEN }}"
    - name: Publish hdf5-derive
      if: "${{ startsWith(github.ref_name, 'hdf5-derive-v') }}"
      run: cargo publish --package hdf5-metno-derive --token "${{ secrets.CRATES_IO_TOKEN }}"
    - name: Publish hdf5-types
      if: "${{ startsWith(github.ref_name, 'hdf5-types-v') }}"
      run: cargo publish --package hdf5-metno-types --token "${{ secrets.CRATES_IO_TOKEN }}"
    - name: Publish hdf5
      if: "${{ startsWith(github.ref_name, 'hdf5-v') }}"
      run: cargo publish --package hdf5-metno --token "${{ secrets.CRATES_IO_TOKEN }}"
